
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: kubediag
    mode: master
  name: kubediag-master-metrics-monitor
  namespace: kubediag
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
    - kubediag
  selector:
    matchLabels:
      control-plane: kubediag
      mode: master
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kubediag
    mode: master
  name: kubediag-master-metrics-monitor
  namespace: kubediag
spec:
  ports:
  - name: metrics
    port: 10357
    targetPort: metrics
  selector:
    control-plane: kubediag
    mode: master
  type: ClusterIP
  clusterIP: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: kubediag
    mode: agent
  name: kubediag-agent-metrics-monitor
  namespace: kubediag
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
    - kubediag
  selector:
    matchLabels:
      control-plane: kubediag
      mode: agent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kubediag
    mode: agent
  name: kubediag-agent-metrics-monitor
  namespace: kubediag
spec:
  ports:
  - name: metrics
    port: 10355
    targetPort: metrics
  selector:
    control-plane: kubediag
    mode: agent
  type: ClusterIP
  clusterIP: None
