apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kubediag
    mode: agent
  name: kubediag-agent-metrics-service
  namespace: kubediag
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: kubediag
    mode: agent
