# permissions for end users to edit operationsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operationset-editor-role
rules:
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operationsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operationsets/status
  verbs:
  - get
