# permissions for end users to edit operations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operation-editor-role
rules:
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operations/status
  verbs:
  - get
