# permissions for end users to view operationsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operationset-viewer-role
rules:
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operationsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operationsets/status
  verbs:
  - get
