apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: core-file-operationset
spec:
  adjacencyList:
    - id: 0
      to:
        - 1
        - 2
    - id: 1
      operation: pod-list-collector
      to:
        - 2
    - id: 2
      operation: core-file-profiler
---
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  name: diagnosis-coreprofiler-example
  namespace: default
spec:
  nodeName: my-node
  operationSet: core-file-operationset
  parameters:
    "param.diagnoser.runtime.core_file_profiler.expiration_seconds": "2000"
    "param.diagnoser.runtime.core_file_profiler.type": "coredump"
  podReference:
    container: test-coredump
    name: testcore-1
    namespace: default
