apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: pod-list-collector
spec:
  adjacencyList:
  - id: 0
    to:
    - 1
  - id: 1
    operation: pod-list-collector
---
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  name: pod-list-collector
spec: 
  operationSet: pod-list-collector
  nodeName: my-node
